# Generated by Django 5.1.3 on 2024-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('E', 'Error')], default='P', max_length=1),
        ),
    ]
